### ISSUE TITLE
API Issues?

### ISSUE THREAD

**Issue by soundmanmiked** [jbasen/Crestron-MyQ#2]
I just loaded this up and programmed it into my own Crestron system and the 'Init Success' is showing that a proper login occurred but I get no feedback on the serial strings nor any door control. Do you know if the API changed and there is a problem or am I doing something wrong?

Thanks for the help!

Mike

**Comment by jbasen** [comment]
Thanks Mike, I think :-)
You are absolutely correct.  Even through I have this in my own Crestron system I hadn't looked at it recently and I'm experiencing the same problem.  I expect that you are correct and that MyQ has change their API, yet again.  They have reputation for breaking integrations.  

It will be a while before I can take a look at this as I have several large projects that I'm dealing with right now.  The full source code is included here, including all the S# so if you have the initiative you can dig in yourself.  Sorry I can't get to this sooner.

**Comment by soundmanmiked** [comment]
No problem, I totally understand. I just wanted to make sure I was not doing something myself. I did look at it for a minute today and loaded up the S# to take a look. The debugger is showing all the correct info returns from MyQ (i.e. device count, names, s/n, etc) its just not parsing correctly to display into the SIMPL module and when an open/close is sent it replies with 'The serial number was invalid. Please try again.' But anyways your code works pretty well considering they must have formatted something different.

**Comment by jbasen** [comment]
I apologize that this has taken me so long to address.  I've uploaded a new version that should address the issue.  The version numbering of the module hasn't changed because all the changes were internal and the SimplWindows interface didn't change.
Thanks

**Comment by soundmanmiked** [comment]
Thank you for all of the hard work you put into these and other interfaces!!!
